-- SQLite
CREATE TABLE user (id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL, hash TEXT NOT NULL, username TEXT NOT NULL, email VARCHAR(320),
elo FLOAT(6,2) NOT NULL);

.schema

SELECT * FROM user;

-- DELETE FROM user;
