-- SQLite
CREATE TABLE user (id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL, hash TEXT NOT NULL, username TEXT NOT NULL, email VARCHAR(320),
elo FLOAT(6,2) NOT NULL);

.schema

SELECT * FROM user;

-- DELETE FROM user;

CREATE TABLE games (game_id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL, player1_id INTEGER, player1_elo SMALLINT, player2_id INTEGER, player2_elo SMALLINT, winner_id INTEGER, time DATETIME);

ALTER TABLE games ADD game_type TEXT;